services:
  devzone-db:
    image: postgres:16-alpine
    container_name: devzone-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  devzone-api-nestjs:
    container_name: devzone-api-nestjs
    build:
      context: .
      #target: development
      target: production
    #command: npm run start:dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - devzone-db
    environment:
      DATABASE_HOST: devzone-db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: postgres
      DATABASE_MIGRATION_ENABLED: "false"
      JWT_SECRET: "secretKey"
