version: '3.5'
services:

  devzone-db:
    image: postgres:14.12-alpine
    container_name: devzone-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  devzone-api-nestjs:
    build:
      context: ../
      #target: development
      target: production
    #command: npm run start:dev
    ports:
      - "18080:8080"
    restart: unless-stopped
    depends_on:
      - devzone-db
    environment:
      DATABASE_HOST: devzone-db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB: postgres
      DATABASE_MIGRATION_ENABLED: "true"
